In [3]:
pip install cfbd

Collecting cfbd
  Downloading cfbd-4.1.8-py3-none-any.whl (300 kB)
     |████████████████████████████████| 300 kB 7.6 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.1 in ./opt/anaconda3/envs/PythonData/lib/python3.6/site-packages (from cfbd) (2.8.1)
Requirement already satisfied: certifi>=2017.4.17 in ./opt/anaconda3/envs/PythonData/lib/python3.6/site-packages (from cfbd) (2020.6.20)
Requirement already satisfied: six>=1.10 in ./opt/anaconda3/envs/PythonData/lib/python3.6/site-packages (from cfbd) (1.15.0)
Requirement already satisfied: urllib3>=1.23 in ./opt/anaconda3/envs/PythonData/lib/python3.6/site-packages (from cfbd) (1.26.6)
Installing collected packages: cfbd
Successfully installed cfbd-4.1.8
Note: you may need to restart the kernel to use updated packages.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import os
from pprint import pprint
import cfbd
import json

In [2]:
# Save config information.
url = "https://api.collegefootballdata.com/teams/fbs"

# Build partial query URL
#response = requests.get(url).json()

In [3]:
configuration = cfbd.Configuration()
configuration.api_key['Authorization'] = '2sina0dm1CRBFSLRL91WQEFQQuY+JWy5tOMOyvCkiE++gayYwQEHNI6aXMsRy4Mi'
configuration.api_key_prefix['Authorization'] = 'Bearer'

In [12]:
# Recruiting Players Call
#api_recruiting = cfbd.RecruitingApi(cfbd.ApiClient(configuration))
#recruiting_2020 = api_recruiting.get_recruiting_players(year=2020)

In [15]:
# Games Call
#api_games = cfbd.GamesApi(cfbd.ApiClient(configuration))
#games_2020 = api_games.get_games(year=2020)

In [6]:
# Teams Call
api_teams = cfbd.TeamsApi(cfbd.ApiClient(configuration))
teams = api_teams.get_teams()

In [4]:
year = 2000
years = []
for i in range(22):
    current_year = year+i
    years.append(current_year)

In [5]:
years

[2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021]

In [7]:
# Recruiting Players Call
recruit_db = []
for current in years: 
    api_recruiting = cfbd.RecruitingApi(cfbd.ApiClient(configuration))
    recruiting = api_recruiting.get_recruiting_players(year=current)
    recruit_db.append(recruiting)

In [13]:
#len(recruiting_2020)

4307

In [14]:
pprint(recruiting_2020[0])

{'athlete_id': 4428988,
 'city': 'Damascus',
 'committed_to': 'Clemson',
 'country': 'USA',
 'height': 77.0,
 'hometown_info': {'fipsCode': '24031',
                   'latitude': '39.2884381',
                   'longitude': '-77.2038717'},
 'id': 61569,
 'name': 'Bryan Bresee',
 'position': 'DT',
 'ranking': 1,
 'rating': 0.9995,
 'recruit_type': 'HighSchool',
 'school': 'Damascus',
 'stars': 5,
 'state_province': 'MD',
 'weight': 290,
 'year': 2020}

In [8]:
recruiting_df = pd.DataFrame()
for recruits in recruit_db:
    
    recruit_df = pd.DataFrame().from_records([
        dict(
            p_id=recruit.id,
            name=recruit.name,
            rating=recruit.rating,
            stars=recruit.stars,
            position=recruit.position,
            college=recruit.committed_to,
            player_lat=recruit.hometown_info['latitude'],
            player_lon=recruit.hometown_info['longitude'],
            state=recruit.state_province,
            country=recruit.country,
            year=recruit.year)
        for recruit in recruits])
#    recruit_df = recruit_df.set_index('p_id')
#    if recruit.state_province is not None and len(c.state_province) == 2 and c.state_province != 'AS' and c.state_province != 'QC' and c.state_province != 'HI'])
    recruiting_df = recruiting_df.append(recruit_df)
#    print(recruit_df)
#    print(recruiting_df)
recruiting_df

,p_id,name,rating,stars,position,college,player_lat,player_lon,state,country,year
0,1,D.J. Williams,0.9998,5,ILB,Miami,37.9768525,-122.0335624,CA,USA,2000
1,2,Brock Berlin,0.9998,5,PRO,Florida,32.5221828,-93.7651944,LA,USA,2000
2,3,Charles Rogers,0.9988,5,WR,Michigan State,43.4200387,-83.9490365,MI,USA,2000
3,4,Travis Johnson,0.9982,5,SDE,Florida State,34.1508718,-118.4489865,CA,USA,2000
4,5,Marcus Houston,0.9980,5,RB,Colorado,39.7392364,-104.9848623,CO,USA,2000
...,...,...,...,...,...,...,...,...,...,...,...
2732,74091,Britton Williams,0.7530,2,K,Georgia Southern,31.9382652,-81.3034433,GA,USA,2021
2733,75815,Zach Zoglio,0.7530,2,LS,Eastern Michigan,39.1014537,-84.5124602,OH,USA,2021
2734,75816,Tanner Luther,0.7530,2,K,Eastern Michigan,39.9405903,-77.6598624,PA,USA,2021
2735,74092,Jabril Williams,0.7491,2,ATH,Army,41.5263603,-88.0840212,IL,USA,2021
2736,75361,Elisha Cummings,0.7441,2,RB,Idaho,31.549333,-97.1466695,TX,USA,2021

In [8]:
len(recruiting_df)

60073

In [17]:
len(games_2020)

542

In [16]:
pprint(games_2020[0])

{'attendance': None,
 'away_conference': None,
 'away_id': 2110,
 'away_line_scores': [7, 14, 0, 14],
 'away_points': 35,
 'away_post_win_prob': 0.0019191196145156297,
 'away_team': 'Central Arkansas',
 'conference_game': False,
 'excitement_index': 2.226002,
 'highlights': 'https://www.youtube.com/watch?v=aBwb65AoLmQ',
 'home_conference': 'Conference USA',
 'home_id': 5,
 'home_line_scores': [14, 14, 3, 14],
 'home_points': 45,
 'home_post_win_prob': 0.9980808803854844,
 'home_team': 'UAB',
 'id': 401238035,
 'neutral_site': False,
 'notes': None,
 'season': 2020,
 'season_type': 'regular',
 'start_date': '2020-09-04T00:00:00.000Z',
 'start_time_tbd': False,
 'venue': 'Legion Field',
 'venue_id': 3803,
 'week': 1}

In [20]:
len(teams_2020)

1697

In [114]:
pprint(teams_2020[207])

{'abbreviation': 'FLA',
 'alt_color': '#0021a5',
 'alt_name_1': None,
 'alt_name_2': None,
 'alt_name_3': None,
 'color': '#0021A5',
 'conference': 'SEC',
 'division': 'East',
 'id': 57,
 'location': {'capacity': 88548,
              'city': 'Gainesville',
              'country_code': 'US',
              'dome': False,
              'elevation': '44.97250748',
              'grass': True,
              'latitude': 29.6499357,
              'longitude': -82.3485788,
              'name': 'Ben Hill Griffin Stadium',
              'state': 'FL',
              'timezone': 'America/New_York',
              'venue_id': 3634,
              'year_constructed': 1930,
              'zip': '32653'},
 'logos': ['http://a.espncdn.com/i/teamlogos/ncaa/500/57.png',
           'http://a.espncdn.com/i/teamlogos/ncaa/500-dark/57.png'],
 'mascot': 'Gators',
 'school': 'Florida'}

In [9]:
team_df = pd.DataFrame().from_records([
        dict(
            school=team.school,
            mascot=team.mascot,
            abv=team.abbreviation,
            conference=team.conference,
            division=team.division,
            color=team.color,
            alt_color=team.alt_color,
            scool_lat=team.location['latitude'],
            school_lon=team.location['longitude'],
            t_id=team.id)
        for team in teams])
#team_df = team_df.set_index('t_id')
team_df

,school,mascot,abv,conference,division,color,alt_color,scool_lat,school_lon,t_id
0,Abilene Christian,Wildcats,ACU,None,None,#4e2683,#ebebeb,NaN,NaN,2000
1,Adams State,Grizzlies,ADST,None,None,#000000,None,NaN,NaN,2001
2,Adrian,Bulldogs,ADR,None,None,#000000,None,NaN,NaN,2003
3,Air Force,Falcons,AFA,Mountain West,Mountain,#004a7b,#ffffff,38.996970,-104.843616,2005
4,Akron,Zips,AKR,Mid-American,East,#00285e,#84754e,41.072553,-81.508341,2006
...,...,...,...,...,...,...,...,...,...,...
1692,Yale Freshmen,None,None,None,None,None,None,NaN,NaN,1000141
1693,Yale/Princeton/Harvard Grads,None,None,None,None,None,None,NaN,NaN,1000084
1694,YMI,None,None,None,None,None,None,NaN,NaN,1000720
1695,York YMCA,None,None,None,None,None,None,NaN,NaN,1000197
1696,Yuma Field,None,None,None,None,None,None,NaN,NaN,1000810

In [10]:
recruit_team_df = recruiting_df.merge(team_df, left_on='college', right_on='school')
#recruit_team_df = recruit_team_df.set_index('p_id')
recruit_team_df

,p_id,name,rating,stars,position,college,player_lat,player_lon,state,country,...,school,mascot,abv,conference,division,color,alt_color,scool_lat,school_lon,t_id
0,1,D.J. Williams,0.9998,5,ILB,Miami,37.9768525,-122.0335624,CA,USA,...,Miami,Hurricanes,MIAMI,ACC,Coastal,#004325,#f0f0f0,25.957967,-80.238860,2390
1,11,Willis McGahee,0.9948,5,RB,Miami,25.7742658,-80.1936589,FL,USA,...,Miami,Hurricanes,MIAMI,ACC,Coastal,#004325,#f0f0f0,25.957967,-80.238860,2390
2,27,Willie Dixon,0.9884,5,WR,Miami,37.9577016,-121.2907796,CA,USA,...,Miami,Hurricanes,MIAMI,ACC,Coastal,#004325,#f0f0f0,25.957967,-80.238860,2390
3,65,Carlos Joseph,0.9759,4,OT,Miami,25.7742658,-80.1936589,FL,USA,...,Miami,Hurricanes,MIAMI,ACC,Coastal,#004325,#f0f0f0,25.957967,-80.238860,2390
4,70,Carl Walker,0.9747,4,S,Miami,30.3321838,-81.655651,FL,USA,...,Miami,Hurricanes,MIAMI,ACC,Coastal,#004325,#f0f0f0,25.957967,-80.238860,2390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52157,65291,Elzie Barnett Jr.,0.7667,2,S,Arkansas-Pine Bluff,32.7762719,-96.7968559,TX,USA,...,Arkansas-Pine Bluff,Golden Lions,UAPB,None,None,#e0aa0f,#eaaa00,34.253327,-92.021403,2029
52158,63004,Jordan Burrell,0.8399,3,CB,Davidson,36.2077351,-119.3473421,CA,USA,...,Davidson,Wildcats,DAV,None,None,#000000,#e51837,NaN,NaN,2166
52159,64051,Elijah Burrell,0.8098,3,DUAL,Davidson,36.2077351,-119.3473421,CA,USA,...,Davidson,Wildcats,DAV,None,None,#000000,#e51837,NaN,NaN,2166
52160,64342,Clarence Freeman,0.7998,3,WR,Davidson,32.83259,-117.2716839,CA,USA,...,Davidson,Wildcats,DAV,None,None,#000000,#e51837,NaN,NaN,2166
52161,64682,Ryan Clark,0.7898,2,DUAL,Bryant,39.9537359,-74.1979576,NJ,USA,...,Bryant,Bulldogs,BRY,None,None,#000000,#9f8343,41.924206,-71.538512,2803

In [11]:
recruit_team_df.head(500)

,p_id,name,rating,stars,position,college,player_lat,player_lon,state,country,...,school,mascot,abv,conference,division,color,alt_color,scool_lat,school_lon,t_id
0,1,D.J. Williams,0.9998,5,ILB,Miami,37.9768525,-122.0335624,CA,USA,...,Miami,Hurricanes,MIAMI,ACC,Coastal,#004325,#f0f0f0,25.957967,-80.238860,2390
1,11,Willis McGahee,0.9948,5,RB,Miami,25.7742658,-80.1936589,FL,USA,...,Miami,Hurricanes,MIAMI,ACC,Coastal,#004325,#f0f0f0,25.957967,-80.238860,2390
2,27,Willie Dixon,0.9884,5,WR,Miami,37.9577016,-121.2907796,CA,USA,...,Miami,Hurricanes,MIAMI,ACC,Coastal,#004325,#f0f0f0,25.957967,-80.238860,2390
3,65,Carlos Joseph,0.9759,4,OT,Miami,25.7742658,-80.1936589,FL,USA,...,Miami,Hurricanes,MIAMI,ACC,Coastal,#004325,#f0f0f0,25.957967,-80.238860,2390
4,70,Carl Walker,0.9747,4,S,Miami,30.3321838,-81.655651,FL,USA,...,Miami,Hurricanes,MIAMI,ACC,Coastal,#004325,#f0f0f0,25.957967,-80.238860,2390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,4237,McIntosh Nicolas,0.9663,4,CB,Florida,26.4186898,-81.4172993,FL,USA,...,Florida,Gators,FLA,SEC,East,#0021A5,#0021a5,29.649936,-82.348579,57
496,4110,Mike McIntosh,0.9222,4,WR,Florida,30.3321838,-81.655651,FL,USA,...,Florida,Gators,FLA,SEC,East,#0021A5,#0021a5,29.649936,-82.348579,57
497,4104,Derrick McPhearson,0.9157,4,WR,Florida,38.9529442,-76.9408647,MD,USA,...,Florida,Gators,FLA,SEC,East,#0021A5,#0021a5,29.649936,-82.348579,57
498,4307,Michael Brown,0.9000,4,DT,Florida,33.7490987,-84.3901849,GA,USA,...,Florida,Gators,FLA,SEC,East,#0021A5,#0021a5,29.649936,-82.348579,57
499,4131,Javier Estopinan,0.9000,4,ILB,Florida,25.7742658,-80.1936589,FL,USA,...,Florida,Gators,FLA,SEC,East,#0021A5,#0021a5,29.649936,-82.348579,57

In [12]:
# Export file as a CSV, without the Pandas index, but with the header
recruit_team_df.to_csv("recruiting_db.csv", header=True)

In [13]:
recruit_team_df.to_json('recruit_team.json', orient = 'records')